sudo: false

language: scala

jdk:
  - openjdk8

matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.5
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
    - scala: 2.12.8
      env: PLAY_VERSION=2.6

cache:
  directories:
    - '$HOME/.ivy2/cache'

notifications:
  email:
    recipients:
      - platform-engineering@digital.hmrc.gov.uk